name: Build and Test

on:
  push:
    branches: ["main"]
    paths-ignore:
      - README.md
      - website/**
      - .github/workflows/publish-website.yml
  pull_request:
    branches: ["main"]
    paths-ignore:
      - README.md
      - website/**
      - .github/workflows/publish-website.yml

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - name: Buildand Test
        run: ./build-and-test.sh
